import Link from 'next/link'    
import Image from 'next/image'
import Layout from '@/components/Layout'
import { GithubIcon } from '@/components/Icons'

import curseage1 from "../../../public/projects/curseage_1.png"
import rivalry1 from "../../../public/projects/rivalry_1.png"
import stylepad from "../../../public/projects/stylepad.png"

export const metadata = {
  title: 'Projects',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

const FeaturedProject = ({type, title, summary, img, link, github}) => {
  return(
    <article className='w-full flex item-center justify-between relative
    rounded-lg shadow-2xl p-4 items-center
    border border-solid border-dark
    dark:bg-dark dark:border-light'>

      <Link href={link} target="_blank" className='h-full w-1/2 cursor-pointer overflow-hidden rounded-lg'>
        <Image src={img} alt={title} className='w-full h-auto' />
      </Link>

      <div className='w-1/2 flex flex-col items-start justify-between pl-6'>
        <span className='text-primary font-medium text-xl dark:text-primaryDark'>{type}</span>
        <Link href={link} target="_blank" className='hover:underline underline-offset-2'>
          <h2 className='my-2 w-full text-left text-4xl font-bold dark:text-light'>{title}</h2>
        </Link>
        <p className='my-2 font-medium'>{summary}</p>
        <div className='mt-2 flex items-center'>
          <Link 
            href={github} 
            target="_blank" 
            className='w-8'>
            <GithubIcon />
          </Link>
          <Link 
            href={link} 
            target="_blank" 
            className='ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold
            dark:bg-light dark:text-dark'>
            Visit Project
          </Link>
        </div>
      </div>

    </article>
  )
}

const Project = ({type, title, summary, img, link, github}) => {
  return(
    <article className='w-full h-full flex flex-col items-center justify-center rounded-2xl p-4 shadow-2xl relative
    border border-solid border-dark
    dark:border-light dark:bg-dark
    '>
      
      <Link href={link} target="_blank" className='w-full h-full cursor-pointer overflow-hidden rounded-lg'>
        <Image src={img} alt={title} className='w-full h-auto' />
      </Link>

      <div className='w-full flex flex-col items-start justify-between mt-4'>
        <span className='text-primary font-medium text-xl dark:text-primaryDark'>{type}</span>
        <Link href={link} target="_blank" className='hover:underline underline-offset-2'>
          <h2 className='my-2 w-full text-left text-3xl font-bold'>{title}</h2>
        </Link>
        <p className='my-2 font-medium'>{summary}</p>
        <div className='w-full mt-2 flex items-center justify-between'>
          <Link href={link} target="_blank" className='text-lg font-semibold underline'>
            Visit
          </Link>
          <Link href={github} target="_blank" className='w-8'>
            <GithubIcon />
          </Link>
        </div>
      </div>

    </article>
  )
}

export default function Projects() {
    return (
      <main>

        {/* Add the Swiper CSS file */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"></link>

        <Layout className='pt-0'>
          
          <h1 className='mt-12 text-4xl font-medium font-title'>Projects</h1>

          <div className='grid grid-cols-12 gap-8'>
            <div className='col-span-12'>
              <FeaturedProject 
              type='Roblox Game'
              title='Curseage'
              summary="An open-world fighting game based on the popular manga series 'Jujutsu Kaisen'."
              link="https://www.roblox.com/games/8294567615/Curseage"
              github="https://github.com/LuwabiProductions"
              img={curseage1}
              />
            </div>
            <div className='col-span-6'>
              <Project
              type='Roblox Game'
              title='Curseage'
              summary="A fantasy genre fighting game."
              link="https://www.roblox.com/games/5211354710/Rivalry-Pre-Alpha"
              github="https://github.com/LuwabiProductions"
              img={rivalry1}
              />
            </div>
            <div className='col-span-6'>
              <Project
              type='Android App'
              title='Stylepad'
              summary="A simple note-taking app."
              link="https://play.google.com/store/apps/details?id=com.davidfadare.notes&pli=1"
              github="https://github.com/LuwabiProductions"
              img={stylepad}
              />
            </div>
          </div>
        </Layout>
      </main>
    )
}